name: myenvschema-3
channels:
  - conda-forge
dependencies:
  - python=3.9  # Specify the Python version you want
  - graphene  # GraphQL library for Python
  - pip
  - pip:
      - aiohttp  # Optional, for async HTTP requests
      - requests
      - mistralai
      - fastapi
      - uvicorn  # Correct name for the ASGI server
      - graphql-core  # GraphQL implementation for Python, if needed
